export const SYONET_COMPANY_ACCESS_DENIED = 'SYONET_COMPANY_ACCESS_DENIED';
export const SYONET_CONTACT_FORM_MAPPING_NOT_FOUND = 'SYONET_CONTACT_FORM_MAPPING_NOT_FOUND';
export const SYONET_EVENT_TYPE_MAPPING_NOT_FOUND = 'SYONET_EVENT_TYPE_MAPPING_NOT_FOUND';
export const SYONET_MEDIA_MAPPING_NOT_FOUND = 'SYONET_MEDIA_MAPPING_NOT_FOUND';

const SYONET_CONFIGURATION_ERROR_CODES = new Set<string>([
  SYONET_COMPANY_ACCESS_DENIED,
  SYONET_CONTACT_FORM_MAPPING_NOT_FOUND,
  SYONET_EVENT_TYPE_MAPPING_NOT_FOUND,
  SYONET_MEDIA_MAPPING_NOT_FOUND,
]);

export function isSyonetConfigurationErrorCode(code: string | undefined): boolean {
  return code !== undefined && SYONET_CONFIGURATION_ERROR_CODES.has(code);
}
